"""init

Revision ID: 1898bc9b6c5e
Revises: dd33cb03d01f
Create Date: 2023-02-24 16:55:52.409909

"""

# revision identifiers, used by Alembic.
revision = '1898bc9b6c5e'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
