"""init

Revision ID: 9733444c9a49
Revises: b88419c304f9
Create Date: 2023-02-24 16:57:48.096609

"""

# revision identifiers, used by Alembic.
revision = '9733444c9a49'
down_revision = 'b88419c304f9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
