"""init

Revision ID: b88419c304f9
Revises: 1898bc9b6c5e
Create Date: 2023-02-24 16:56:53.216509

"""

# revision identifiers, used by Alembic.
revision = 'b88419c304f9'
down_revision = '1898bc9b6c5e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
