"""init

Revision ID: d3ee37d222d3
Revises: 9733444c9a49
Create Date: 2023-02-24 17:08:26.641191

"""

# revision identifiers, used by Alembic.
revision = 'd3ee37d222d3'
down_revision = '9733444c9a49'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
